account/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url(r'^zaloguj/$', views.user_login, name='login'),
    url(r'zaloguj/$', 'django.contrib.auth.views.login', name='login'),
    url(r'wyloguj/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'wyloguj-i-zaloguj/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),
    url(r'^$', views.dashboard, name='dashboard'),
    # change password urls
    url(r'^password-change/$',
        'django.contrib.auth.views.password_change',
        name='password_change'),
    url(r'^password-change/done/$',
        'django.contrib.auth.views.password_change_done',
        name='password_change_done'),
    url(r'^zarejestruj/$', views.register, name='register'),
    url(r'^edycja/$', views.edit, name='edit'),
    url('social-auth/',
        include('social.apps.django_app.urls', namespace='social')),
    ]

blog/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
                       url(r'^post/nowy/$', views.post_new, name='post_new'),
                       url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
                       url(r'^post/(?P<pk>[0-9]+)/edycja/$', views.post_edit, name='post_edit'),
                       url(r'^$', views.post_list, name='post_list'),
                       url(r'^tag/(?P<tag_slug>[-\w]+)/$',
                           views.post_list,
                           name='post_list_by_tag'),
)

iskra/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^konto/', include('account.urls')),
    # sending emails
    url(r'^kontakt/wyslij-wiadomosc/$', 'account.views.send_email_to_me'),
    url(r'^kontakt/$', 'account.views.contact'),
    # views for 'sekcje'
    url(r'^sekcje/wszystkie/$', 'account.views.sekcje', name='sekcje-wszystkie'),
    url(r'^sekcje/zeglarstwo/$', 'account.views.zeglarstwo', name='sekcje-zeglarstwo'),
    url(r'^sekcje/lekkoatletyka/$', 'account.views.lekkoatletyka', name='sekcje-lekkoatletyka'),
    url(r'^sekcje/futsal/$', 'account.views.futsal', name='sekcje-futsal'),
    url(r'^sekcje/plywanie/$', 'account.views.plywanie', name='sekcje-plywanie'),
    url(r'^sekcje/badminton/$', 'account.views.badminton', name='sekcje-badminton'),

    url(r'^$', 'account.views.main_page', name='main_page'),
    # calendar from django-calendarium
    url(r'^kalendarz/', include('calendarium.urls')),
    # now logged user (not only staff members) can upload images
    url(r'^ckeditor/upload/',
        login_required(upload),
        name='ckeditor_upload'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls',
                           namespace='blog_namespace',
                           app_name='blog')),
    url(r'^newsy/$', 'blog.views.news_list'),
    url(r'^newsy/nowy/$', 'blog.views.news_new', name='news_new'),
    url(r'^newsy/news/(?P<pk>[0-9]+)/$', 'blog.views.news_detail', name='news_detail'),
    url(r'^newsy/news/(?P<pk>[0-9]+)/edycja/$', 'blog.views.news_edit', name='news_edit'),
    url(r'^ciekawostki/', include('sharings.urls', namespace='sharings')),
    url(r"^search/", include("watson.urls", namespace="watson")),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sharings/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^tworzenie/$', views.sharing_create, name='create'),
    url(r'^detale/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.image_detail, name='detail'),
    url(r'^polubienia/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    ]

account/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return 'Profil dla użytkownika {}'.format(self.user.username)

    def __unicode__(self):
        return self.user

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Hasło",
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label="Powtórz hasło",
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Hasła się nie zgadzają!!!')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.mail import BadHeaderError, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.text import slugify
from .forms import LoginForm, UserRegistrationForm, \
    UserEditForm, ProfileEditForm
from .models import Profile


# dashboard of current user
@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html')


# sending mail under 'Kontakt' tab
def send_email_to_me(request):
    fullname = slugify(request.POST.get('fullname'))
    message = request.POST.get('message')
    from_email = request.POST.get('from_email')
    subject = 'Masz wiadomość ze strony KS Iskra od {}'.format(fullname)
    email = EmailMessage(subject, message, 'kontakt@iskra-amw.org.pl',
                         ['I.Kaminski@amw.gdynia.pl'],
                         bcc=['a.zacniewski@interia.eu'],
                         headers={'Reply-To': from_email})
    try:
        email.content_subtype = "html"  # Main content is now text/html
        email.send(fail_silently=False)
    except BadHeaderError:
        return HttpResponse('Invalid header found.')
    return HttpResponseRedirect('/kontakt/')


# log-in
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Zalogowano poprawnie')
                else:
                    return HttpResponse('Konto zablokowane')
            else:
                return HttpResponse(u'Błędne logowanie')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


# register new users
def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # new user (not saved yet)
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            # now, we can save new user
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request,
                          'account/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
        return render(request,
                      'account/register.html',
                      {'user_form': user_form})


# edit your profile
@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profil zaktualizowany pomyślnie')
        else:
            messages.error(request, 'Problem z uaktualnieniem profilu')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


# view for the main page
def main_page(request):
    return render(request, 'account/main-page.html')


# view for the 'calendar' page
def calendar(request):
    return render(request, 'account/calendar.html')


# contact view
def contact(request):
    return render(request, 'account/contact.html')


# views for the 'sekcje' page
def sekcje(request):
    return render(request, 'account/sekcje.html')


def zeglarstwo(request):
    return render(request, 'account/zeglarstwo.html')


def lekkoatletyka(request):
    return render(request, 'account/lekkoatletyka.html')


def futsal(request):
    return render(request, 'account/pilka-halowa.html')


def plywanie(request):
    return render(request, 'account/plywanie.html')


def badminton(request):
    return render(request, 'account/badminton.html')

account/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Klub Sportowy "ISKRA" przy Akademii Marynarki Wojennej</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >

    <!-- Custom CSS -->
    <link href="{% static 'css/iskra.css' %}" rel="stylesheet">
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

    <!--Favicon-->
    <link rel="icon" type="image/png" href="{% static 'images/favicon-iskra.png' %}">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- Files for django-calendarium-->
    <link rel="stylesheet" href="{% static 'calendarium/css/calendar2.css' %}">

    <!-- jQuery -->
    <!--<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>-->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <!--FancyBox-->
    <!-- Add mousewheel plugin (this is optional) -->
    <script type="text/javascript" src="{% static 'fancybox/lib/jquery.mousewheel-3.0.6.pack.js' %}"></script>

    <!-- Add fancyBox -->
    <link rel="stylesheet" href="{% static 'fancybox/source/jquery.fancybox.css' %}" type="text/css" media="screen" />
    <script type="text/javascript" src="{% static 'fancybox/source/jquery.fancybox.pack.js' %}"></script>

    <!-- Optionally add helpers - button, thumbnail and/or media -->
    <link rel="stylesheet" href="{% static 'fancybox/source/helpers/jquery.fancybox-buttons.css' %}" type="text/css" media="screen" />
    <script type="text/javascript" src="{% static 'fancybox/source/helpers/jquery.fancybox-buttons.js' %}"></script>
    <script type="text/javascript" src="{% static 'fancybox/source/helpers/jquery.fancybox-media.js' %}"></script>

    <link rel="stylesheet" href="{% static 'fancybox/source/helpers/jquery.fancybox-thumbs.css' %}" type="text/css" media="screen" />
    <script type="text/javascript" src="{% static 'fancybox/source/helpers/jquery.fancybox-thumbs.js' %}"></script>

    <!-- Sticky footer -->
    <script type="text/javascript" src="{% static 'js/jquery.stickyfooter.min.js' %}"></script>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Analytics-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-32924821-2', 'auto');
      ga('send', 'pageview');

</script>

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'account.views.main_page' %}">KS Iskra</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'account.views.sekcje' %}">Sekcje</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Aktualności <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'blog.views.news_list' %}">Newsy</a>
                            </li>
                            <li>
                                <a href="{% url 'blog.views.news_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> Dodaj newsa</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <!--<a href="/kalendarz/">Kalendarz sportowy</a>-->
                        <a href="{% url 'calendar_current_month' %}">Kalendarz</a>
                    </li>
                    <li>
                        <a href="{% url 'sharings:list' %}">Ciekawostki</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'blog:post_list' %}">Posty klubowiczów</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> Dodaj post</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'account.views.contact' %}">Kontakt</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Inne <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#" id="o-klubie">O klubie</a>
                            </li>
                            <li>
                                <a href="#" id="wladze-klubu">Władze klubu</a>
                            </li>
                            <li>
                                <a href="{% static 'assets/Deklaracja-Iskra.zip' %}">
                                    Deklaracja członkostwa &nbsp; <i class="fa fa-file-archive-o fa-lg"></i>
                                    </a>
                            </li>
                            <li>
                                <a href="{% static 'assets/Darowizna-Iskra.zip' %}">
                                    Druk darowizny &nbsp; <i class="fa fa-file-archive-o fa-lg"></i>
                                    </a>
                            </li>
                            <li>
                                <a href="{% static 'assets/Dodawanie-obrazkow.pdf' %}">
                                    Instrukcja dodawania obrazków &nbsp; <i class="fa fa-file-pdf-o fa-lg"></i>
                                    </a>
                            </li>
                            <li>
                                <a href="#" id="acs">ACS</a>
                            </li>
                            <li>
                                <a href="http://khaos.nazwa.pl/iskra/" target="_blank">Starsza strona klubu</a>
                            </li>

                        </ul>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'dashboard' %}"><i class="fa fa-cog fa-spin"></i> Mój panel</a>
                        </li>
                    {% endif %}
                    <li>
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'logout' %}?next=/">Wyloguj się, {{ request.user.first_name }}</a>
                        {% else %}
                        <a href="{% url 'login' %}">Zaloguj</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- 'messages' framework -->
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="{% url 'dashboard' %}" class="close">✖</a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}


    {% block content %}
        {% block main %}
        <!-- block 'main' is necessary for django-calendarium-->
        {% endblock %}
    {% endblock %}

    <!-- Footer -->
    <footer id="footer">
        <div class="row">
            <div class="col-lg-12">
                <p style="text-align: center"> &copy; KS "Iskra" przy AMW, 1997 - 2016</p>
            </div>
        </div>
    </footer>

    <!--</div>-->
        <!-- /.container -->
    <!--Interaction with cookies-->
    <script src=" http://cdn.jsdelivr.net/jquery.cookie/1.4.1/jquery.cookie.min.js "></script>
    <!--checking the DOM-->
    <script>
        var csrftoken = $.cookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
        $(document).ready(function(){
            {% block domready %}
            {% endblock %}
        });
    </script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <!-- modals for 'Inne' tab -->
    {% include "account/wladze-klubu.html" %}
    {% include "account/o-klubie.html" %}
    {% include "account/acs.html" %}

    <!--modals in 'Inne' section-->
    <script>
    $(document).ready(function() {
        $("#wladze-klubu").click(function () {
            $("#myModal").modal();
            });
        $("#o-klubie").click(function () {
            $("#myModal2").modal();
            });
        $("#acs").click(function () {
            $("#myModal3").modal();
            });
        });
    </script>


    <!-- Right click disabled-->
   <!-- <script>
        $(function(){
            $(document).on("contextmenu",function(e){
            e.preventDefault();
            });
            });
    </script>-->
    <!-- JS specific for given page -->
    {% block js-scripts %}
    {% endblock %}

</body>

</html>