blog/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
                       url(r'^post/nowy/$', views.post_new, name='post_new'),
                       url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
                       url(r'^post/(?P<pk>[0-9]+)/edycja/$', views.post_edit, name='post_edit'),
                       url(r'^$', views.post_list, name='post_list'),
                       url(r'^tag/(?P<tag_slug>[-\w]+)/$',
                           views.post_list,
                           name='post_list_by_tag'),
)

iskra/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^konto/', include('account.urls')),
    # sending emails
    url(r'^kontakt/wyslij-wiadomosc/$', 'account.views.send_email_to_me'),
    url(r'^kontakt/$', 'account.views.contact'),
    # views for 'sekcje'
    url(r'^sekcje/wszystkie/$', 'account.views.sekcje', name='sekcje-wszystkie'),
    url(r'^sekcje/zeglarstwo/$', 'account.views.zeglarstwo', name='sekcje-zeglarstwo'),
    url(r'^sekcje/lekkoatletyka/$', 'account.views.lekkoatletyka', name='sekcje-lekkoatletyka'),
    url(r'^sekcje/futsal/$', 'account.views.futsal', name='sekcje-futsal'),
    url(r'^sekcje/plywanie/$', 'account.views.plywanie', name='sekcje-plywanie'),
    url(r'^sekcje/badminton/$', 'account.views.badminton', name='sekcje-badminton'),

    url(r'^$', 'account.views.main_page', name='main_page'),
    # calendar from django-calendarium
    url(r'^kalendarz/', include('calendarium.urls')),
    # now logged user (not only staff members) can upload images
    url(r'^ckeditor/upload/',
        login_required(upload),
        name='ckeditor_upload'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls',
                           namespace='blog_namespace',
                           app_name='blog')),
    url(r'^newsy/$', 'blog.views.news_list'),
    url(r'^newsy/nowy/$', 'blog.views.news_new', name='news_new'),
    url(r'^newsy/news/(?P<pk>[0-9]+)/$', 'blog.views.news_detail', name='news_detail'),
    url(r'^newsy/news/(?P<pk>[0-9]+)/edycja/$', 'blog.views.news_edit', name='news_edit'),
    url(r'^ciekawostki/', include('sharings.urls', namespace='sharings')),
    url(r"^search/", include("watson.urls", namespace="watson")),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
#from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from watson import search as watson
from taggit.managers import TaggableManager


class Post(models.Model):
    CATEGORY_CHOICES = (
        ('blogowy', 'Do blogu'),
        ('newsowy', 'Do aktualności'),
        )
    author = models.ForeignKey(User)
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(
        default=timezone.now)
    published_date = models.DateTimeField(
        default=timezone.now)
    category = models.CharField(max_length=10,
                                choices=CATEGORY_CHOICES,
                                default='newsowy')

    def publish(self):
        self.published_date = timezone.now
        #self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.pk])

    tags = TaggableManager()

"""
Wiki says that it should be done in Django <1.6,
but in my case searching doesn't work without it
https://github.com/etianen/django-watson/wiki
"""
watson.register(Post)

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'category')

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
#from django.core.urlresolvers import reverse
from taggit.models import Tag
from .models import Post
from .forms import PostForm


# posty blogowe
def post_list(request, tag_slug=None):
    object_list = Post.objects.filter(category__icontains='blogowy').order_by('-published_date')
    tag = None
    all_tags = Tag.objects.all()
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag,
                   'all_tags': all_tags})


# aktualności
def news_list(request):
    object_list = Post.objects.filter(category__icontains='newsowy').order_by('-published_date')
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/news_list.html', {'posts': posts})


# szczegóły postu
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


# szczegóły newsa
def news_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/news_detail.html', {'post': post})


# nowy post
@login_required()
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog_namespace:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


# nowy news
@login_required()
def news_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog.views.news_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/news_edit.html', {'form': form})


# edycja postu
@login_required()
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #post.publish()
            post.save()
            return redirect('blog_namespace:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


# edycja newsa
@login_required()
def news_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #post.publish()
            post.save()
            return redirect('blog.views.news_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

blog/templates/blog/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/news_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="row text-justify">
            {% if post.published_date %}
                <p class="lead">
                    Dodany przez <strong style="color: #0000C0">{{ post.author }}</strong>, <i class="fa fa-clock-o"></i> {{ post.published_date }}
                </p>
            {% endif %}
            {% if request.user == post.author %}
            <a class="btn btn-default" href="{% url 'blog.views.news_edit' pk=post.pk %}">Edytuj news <span class="glyphicon glyphicon-pencil"></span></a>
            {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|safe|linebreaks }}</p>
    </div>
</div>
{% endblock %}
{% block js-scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script>
        $("a").attr('rel', 'pictures_group');
        $("a.obrazek").fancybox({
		'transitionIn'		: 'none',
		'transitionOut'		: 'none',
		'titlePosition' 	: 'over',
		'titleFormat'       : function(title, currentArray, currentIndex, currentOpts) {
		    return '<span id="fancybox-title-over">Zdjęcie ' +  (currentIndex + 1) + ' / ' + currentArray.length + ' ' + title + '</span>';
		}
	});
    </script>
{% endblock %}

blog/templates/blog/news_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load add_css %}

{% block content %}
    <div class="container">
    <!-- Page Heading/Breadcrumbs -->
      <div class="row">
          <div class="modal-content col-lg-10-8 col-md-offset-1">
            <div class="modal-header">
              <h4 style="color:red;"><span class="glyphicon glyphicon-edit"></span> Nowy wpis</h4>
            </div>
            <div class="modal-body">
              <form action="." method="post">
                <div class="form-group">
                  {{ form.title.errors }}
                  <label for="id_title"><span class="glyphicon glyphicon-bookmark"></span> Tytuł:</label>
                  {{ form.title|addcss:"form-control" }}
                </div>
                <div class="form-group">
                    {{ form.category.errors }}
                    <label for="id_category"><span class="glyphicon glyphicon-book"></span> Wybierz kategorię wpisu</label>
                    {{ form.category|addcss:"form-control" }}
                </div>
                <div class="form-group">
                    {{ form.text.errors }}
                    <label for="id_text"><span class="glyphicon glyphicon-book"></span> Treść:</label>
                    {{ form.text|addcss:"form-control" }}
                </div>

                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-success btn-block"><span class="glyphicon glyphicon-save"></span> Zapisz zmiany</button>
              </form>
            </div>
            <div class="modal-footer">
              <button id="anuluj" type="submit" class="btn btn-default btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Anuluj</button>
            </div>
          </div>
        </div>
    </div>

{% endblock %}
{% block js-scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type='text/javascript' src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script>
      $(document).ready(function(){
          $("#anuluj").click(function(){
              window.location.href = "{% url 'main_page' %}";
          });
      });
    </script>

{% endblock %}

blog/templates/blog/news_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load staticfiles %}
{% block content %}
<!--<div class="container">
<div class="row text-center">
    Dodaj post <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
</div>
    {% for post in posts %}
        <div class="row text-justify">
            <h3><a href="{% url 'blog:post_edit' pk=post.pk %}">{{ post.title|upper }}</a></h3>
            <p>Data publikacji: {{ post.published_date }}, autor: {{ post.author }}</p>
            {{ post.text|safe}}
        </div>
    {% endfor %}
</div>-->

<!-- Page Content -->
    <div class="container">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Aktualności
                    <small>KS Iskra</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-10 col-md-offset-1">
                <!--  Blog Posts -->
                {% for post in posts %}
                <h2>
                    {{ post.title }}
                    {% if request.user == post.author %}
                        <a class="btn btn-default" href="{% url 'blog.views.news_edit' pk=post.pk %}">Edytuj post <span class="glyphicon glyphicon-pencil"></span></a>
                    {% endif %}
                </h2>
                <p class="lead">
                    Dodany przez <strong style="color: #0000C0">{{ post.author }}</strong>, <i class="fa fa-clock-o"></i> {{ post.published_date }}</p>
                <hr>
                <div class="text-justify">
                    {{ post.text|safe}}
                </div>
                <!--<a class="btn btn-primary" href="#">Więcej <i class="fa fa-angle-right"></i></a>-->
                <hr>
                {% endfor %}

                <!--Pagination-->
                <ul class="pager">
                    {% with page=posts %}
                        {% if page.has_previous %}
                        <li class="previous">
                            <a href="?page={{ page.previous_page_number }}">&larr; Poprzednia</a>
                        </li>
                        {% endif %}
                        <span class="current">
                            Strona {{ page.number }} z {{ page.paginator.num_pages }}
                        </span>
                        {% if page.has_next %}
                        <li class="next">
                            <a href="?page={{ page.next_page_number }}">&rarr; Następna</a>
                        </li>
                        {% endif %}
                    {% endwith %}
                </ul>

            </div>



        </div>
        <!-- /.row -->

        <hr>
    </div>

    <!-- /.container -->
{% endblock content %}
{% block js-scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script>
        $("a").attr('rel', 'pictures_group');
        $("a.obrazek").fancybox({
		'transitionIn'		: 'none',
		'transitionOut'		: 'none',
		'titlePosition' 	: 'over',
		'titleFormat'       : function(title, currentArray, currentIndex, currentOpts) {
		    return '<span id="fancybox-title-over">Zdjęcie ' +  (currentIndex + 1) + ' / ' + currentArray.length + ' ' + title + '</span>';
		}
	});

    </script>
{% endblock %}

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
    {% endif %}
    <span class="current">
        Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
    {% endif %}
    </span>
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="row text-justify">
            {% if post.published_date %}
                <p class="lead">
                    Dodany przez <strong style="color: #0000C0">{{ post.author }}</strong>, <i class="fa fa-clock-o"></i> {{ post.published_date }}
                </p>
            {% endif %}
            {% if request.user == post.author %}
            <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}">Edytuj post <span class="glyphicon glyphicon-pencil"></span></a>
            {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|safe|linebreaks }}</p>
    </div>
</div>
{% endblock %}
{% block js-scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>

    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script>
        $("a").attr('rel', 'pictures_group');
        $("a.obrazek").fancybox({
		'transitionIn'		: 'none',
		'transitionOut'		: 'none',
		'titlePosition' 	: 'over',
		'titleFormat'       : function(title, currentArray, currentIndex, currentOpts) {
		    return '<span id="fancybox-title-over">Zdjęcie ' +  (currentIndex + 1) + ' / ' + currentArray.length + ' ' + title + '</span>';
		}
	});
    </script>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load add_css %}

{% block content %}
    <div class="container">
    <!-- Page Heading/Breadcrumbs -->
      <div class="row">
          <div class="modal-content col-lg-10-8 col-md-offset-1" style="margin-left: auto;">
            <div class="modal-header">
              <h4 style="color:red;"><span class="glyphicon glyphicon-edit"></span> Nowy wpis</h4>
            </div>
            <div class="modal-body" style="width: 100%">
              <form action="." method="post" style="padding: 0px">
                <div class="form-group">
                  {{ form.title.errors }}
                  <label for="id_title"><span class="glyphicon glyphicon-bookmark"></span> Tytuł:</label>
                  {{ form.title|addcss:"form-control" }}
                </div>
                <div class="form-group">
                    {{ form.category.errors }}
                    <label for="id_category"><span class="glyphicon glyphicon-book"></span> Wybierz kategorię wpisu</label>
                    {{ form.category|addcss:"form-control" }}
                </div>
                <div class="form-group">
                    {{ form.text.errors }}
                    <label for="id_text"><span class="glyphicon glyphicon-book"></span> Treść:</label>
                    {{ form.text|addcss:"form-control" }}
                </div>

                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-success btn-block"><span class="glyphicon glyphicon-save"></span> Zapisz zmiany</button>
              </form>
            </div>
            <div class="modal-footer">
              <button id="anuluj" type="submit" class="btn btn-default btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Anuluj</button>
            </div>
          </div>
        </div>
    </div>

{% endblock %}
{% block js-scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type='text/javascript' src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script>
      $(document).ready(function(){
          $("#anuluj").click(function(){
              window.location.href = "{% url 'main_page' %}";
          });
      });
    </script>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load staticfiles %}
{% load watson %}
{% block content %}
<!--<div class="container">
<div class="row text-center">
    Dodaj post <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
</div>
    {% for post in posts %}
        <div class="row text-justify">
            <h3><a href="{% url 'blog:post_edit' pk=post.pk %}">{{ post.title|upper }}</a></h3>
            <p>Data publikacji: {{ post.published_date }}, autor: {{ post.author }}</p>
            {{ post.text|safe}}
        </div>
    {% endfor %}
</div>-->

<!-- Page Content -->
<div class="container" xmlns="http://www.w3.org/1999/html">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Blog
                    <small>KS Iskra</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <!--  Blog Posts -->
                {% if tag %}
                    <h1 class="text-center">Posty z kategorii "{{ tag.name }}":</h1>
                {% endif %}
                {% for post in posts %}
                <h2>
                    {{ post.title }}
                    {% if request.user == post.author %}
                        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}">Edytuj post <span class="glyphicon glyphicon-pencil"></span></a>
                    {% endif %}
                </h2>
                <p class="lead">
                    Dodany przez <strong style="color: #0000C0">{{ post.author.first_name }}&nbsp;{{ post.author.last_name }}</strong>, <i class="fa fa-clock-o"></i> {{ post.published_date }},
                    <span class="tags">kat.:
                        {% for tag in post.tags.all %}
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                {{ tag.name }}
                            </a>
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </span>
                </p>
                <hr>
                <div class="text-justify">
                    {{ post.text|safe|truncatewords:70}}
                    <a class="btn btn-primary" href="{{ post.get_absolute_url }}">Więcej</i></a>
                </div>
                <!--<a class="btn btn-primary" href="#">Więcej <i class="fa fa-angle-right"></i></a>-->
                <hr>
                {% endfor %}

                <!--Pagination-->
                <ul class="pager">
                    {% with page=posts %}
                        {% if page.has_previous %}
                        <li class="previous">
                            <a href="?page={{ page.previous_page_number }}">&larr; Poprzednia</a>
                        </li>
                        {% endif %}
                        <span class="current">
                            Strona {{ page.number }} z {{ page.paginator.num_pages }}
                        </span>
                        {% if page.has_next %}
                        <li class="next">
                            <a href="?page={{ page.next_page_number }}">&rarr; Następna</a>
                        </li>
                        {% endif %}
                    {% endwith %}
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Szukaj w blogu:</h4>
                    <div class="input-group">
                        <form action="{% url 'watson:search' %}">
                            <input name="q" value="{{request.GET.q}}">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Kategorie</h4>
                    <div class="row">
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            {% for tag in all_tags %}
                                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                    {{ tag.name }}<br/>
                                </a>
                            {% endfor %}
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Liczba wpisów na blogu - {% total_posts %}</h4>
                    <h4>Ostatnie posty:</h4>
                    {% show_latest_posts 5 %}
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>
    </div>

    <!-- /.container -->
{% endblock content %}
{% block js-scripts %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script>
        $("a").attr('rel', 'pictures_group');
        $("a.obrazek").fancybox({
		'transitionIn'		: 'none',
		'transitionOut'		: 'none',
		'titlePosition' 	: 'over',
		'titleFormat'       : function(title, currentArray, currentIndex, currentOpts) {
		    return '<span id="fancybox-title-over">Zdjęcie ' +  (currentIndex + 1) + ' / ' + currentArray.length + ' ' + title + '</span>';
		}
	});
    </script>
{% endblock %}
