blog/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
                       url(r'^post/nowy/$', views.post_new, name='post_new'),
                       url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
                       url(r'^post/(?P<pk>[0-9]+)/edycja/$', views.post_edit, name='post_edit'),
                       url(r'^$', views.post_list, name='post_list'),
                       url(r'^tag/(?P<tag_slug>[-\w]+)/$',
                           views.post_list,
                           name='post_list_by_tag'),
)

iskra/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from ckeditor_uploader.views import upload

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^konto/', include('account.urls')),
    # sending emails
    url(r'^kontakt/wyslij-wiadomosc/$', 'account.views.send_email_to_me'),
    url(r'^kontakt/$', 'account.views.contact'),
    # views for 'sekcje'
    url(r'^sekcje/wszystkie/$', 'account.views.sekcje', name='sekcje-wszystkie'),
    url(r'^sekcje/zeglarstwo/$', 'account.views.zeglarstwo', name='sekcje-zeglarstwo'),
    url(r'^sekcje/lekkoatletyka/$', 'account.views.lekkoatletyka', name='sekcje-lekkoatletyka'),
    url(r'^sekcje/futsal/$', 'account.views.futsal', name='sekcje-futsal'),
    url(r'^sekcje/plywanie/$', 'account.views.plywanie', name='sekcje-plywanie'),
    url(r'^sekcje/badminton/$', 'account.views.badminton', name='sekcje-badminton'),

    url(r'^$', 'account.views.main_page', name='main_page'),
    # calendar from django-calendarium
    url(r'^kalendarz/', include('calendarium.urls')),
    # now logged user (not only staff members) can upload images
    url(r'^ckeditor/upload/',
        login_required(upload),
        name='ckeditor_upload'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls',
                           namespace='blog_namespace',
                           app_name='blog')),
    url(r'^newsy/$', 'blog.views.news_list'),
    url(r'^newsy/nowy/$', 'blog.views.news_new', name='news_new'),
    url(r'^newsy/news/(?P<pk>[0-9]+)/$', 'blog.views.news_detail', name='news_detail'),
    url(r'^newsy/news/(?P<pk>[0-9]+)/edycja/$', 'blog.views.news_edit', name='news_edit'),
    url(r'^ciekawostki/', include('sharings.urls', namespace='sharings')),
    url(r"^search/", include("watson.urls", namespace="watson")),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sharings/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^tworzenie/$', views.sharing_create, name='create'),
    url(r'^detale/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.image_detail, name='detail'),
    url(r'^polubienia/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
    ]

sharings/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.text import slugify


class Sharing(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='sharings_created')
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,
                            blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True,
                               db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='sharings_liked',
                                       blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Sharing, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('sharings:detail',
                       args=[self.id, self.slug])

sharings/forms.py
from urllib import request
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
from .models import Sharing


class SharingCreateForm(forms.ModelForm):
    class Meta:
        model = Sharing
        fields = ['title', 'url', 'description']
        # URL will be received without typing
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("Podany adres URL nie zawiera '\
            'dopuszczalnego rozszerzenia (.jpeg lub .jpg lub .png)")
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super(SharingCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())

        # download image
        response = request.urlopen(image_url)
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

sharings/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from django.views.decorators.http import require_POST, require_GET
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from common.decorators import ajax_required
from .forms import SharingCreateForm
from .models import Sharing


@login_required()
def sharing_create(request):
    if request.method == 'POST':
        form = SharingCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_item = form.save(commit=False)

            # assign user
            new_item.user = request.user
            new_item.save()
            messages.success(request, 'Dodano zasób z powodzeniem!')
            return redirect(new_item.get_absolute_url())
    else:
        form = SharingCreateForm(data=request.GET)
    return render(request, 'sharings/image/create.html',
                  {'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Sharing, id=id, slug=slug)
    return render(request,
                  'sharings/image/detail.html',
                  {'image':image})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Sharing.objects.get(id=image_id)
            if action=='like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ko'})


def image_list(request):
    images = Sharing.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # If the request is AJAX and the page is out of range return an empty page
            return HttpResponse('')
        # If page is out of range deliver last page of results
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'sharings/image/list_ajax.html',
                      {'images': images})
    return render(request,
                  'sharings/image/list.html',
                   {'images': images})

sharings/templates/sharings/image/create.html
{% extends "base.html" %}
{% block title %}Zaznaczanie obrazu{% endblock %}
{% block content %}
    <h1>Dodawanie zdjęcia</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Dodaj ciekawostkę">
    </form>
{% endblock %}
{% block js-scripts %}
    <!-- Sticky footer-->
    <script>
        $(window).load(function() {
    $("#footer").stickyFooter();
            });
    </script>
{% endblock %}

sharings/templates/sharings/image/detail.html
{% extends "base.html" %}

{% block title %}{{ image.title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1>{{ image.title }}</h1>
            {% load thumbnail %}

            <a href="{{ image.image.url }}">
                <img src="{% thumbnail image.image 400x400 crop %}" class="image-detail">
            </a>
            {% with total_likes=image.users_like.count users_like=image.users_like.all %}
                <div class="image-info">
                        <div>
                            <span class="count">
                                <span class="total">{{ total_likes }}</span>
                                polubień
                            </span>
                            <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                                {% if request.user not in users_like %}
                                    Polub
                                {% else %}
                                    Przestań lubić
                                {% endif %}
                            </a>
                        </div>
                        <p>Dodany przez: <span style="color:blue;">{{ image.user }}</span></p>
                        <p>Adres WWW: {{image.url }}</p>
                        <p> Komentarz: {{ image.description }} </p>
                </div>
        </div>
        <div class="row">
            <h3>Polubienia:</h3>
                <div class="image-likes col-lg-8">
                    {% for user in image.users_like.all %}
                        <div>
                            <img src="{{ user.profile.photo.url }}">
                            <p>{{ user.first_name }}</p>
                        </div>
                    {% empty %}
                        Nikt tego jeszcze nie polubił.
                    {% endfor %}
                </div>
            {% endwith %}
        </div>
    </div>

{% endblock %}

{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "sharings:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                if (data['status'] == 'ok')
                {
                    var previous_action = $('a.like').data('action');

                    // toggle data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('a.like').text(previous_action == 'like' ? 'Przestań lubić' : 'Polub');

                    // update total likes
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                }
        });

    });
{% endblock %}
{% block js-scripts %}
    <!-- Sticky footer-->
    <script>
        $(window).load(function() {
    $("#footer").stickyFooter();
            });
    </script>
{% endblock %}

sharings/templates/sharings/image/list.html
{% extends "base.html" %}

{% block title %}Images bookmarked{% endblock %}

{% block content %}
    <h1 class="text-center">Ciekawostki klubowiczów</h1>
    <div id="image-list">
        {% include "sharings/image/list_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
		    block_request = true;
		    page += 1;
		    $.get('?page=' + page, function(data) {
		        if(data == '')
		        {
		            empty_page = true;
		        }
		        else {
                    block_request = false;
                    $('#image-list').append(data);
    	        }
            });
    	}
    });
{% endblock %}
{% block js-scripts %}
    <!-- Sticky footer-->
    <script>
        $(window).load(function() {
    $("#footer").stickyFooter();
            });
    </script>
{% endblock %}

sharings/templates/sharings/image/list_ajax.html
{% load thumbnail %}

<div class="container">
{% for image in images %}
    <div class="image">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop="100%" as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}">
                </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
        </div>
    </div>
{% endfor %}
</div>